<?php

$arr = array(
    "code"=>"1",
    "result"=>array(
        "data"=>array(
            array(
                "name"=>"linjie3",
                "telephone"=>"15659871332",
                "country"=>"中国",
                "referee"=>"4",
                "proxyLevel"=>"0",
                "capital"=>"0"
            ),
            array(
                "name"=>"linjie3",
                "telephone"=>"15659871332",
                "country"=>"中国",
                "referee"=>"4",
                "proxyLevel"=>"0",
                "capital"=>"0"
            ),
            array(
                "name"=>"linjie3",
                "telephone"=>"15659871332",
                "country"=>"中国",
                "referee"=>"4",
                "proxyLevel"=>"0",
                "capital"=>"0"
            ),
            array(
                "name"=>"linjie3",
                "telephone"=>"15659871332",
                "country"=>"中国",
                "referee"=>"4",
                "proxyLevel"=>"0",
                "capital"=>"0"
            ),
            array(
                "name"=>"linjie3",
                "telephone"=>"15659871332",
                "country"=>"中国",
                "referee"=>"4",
                "proxyLevel"=>"0",
                "capital"=>"0"
            ),
            array(
                "name"=>"linjie3",
                "telephone"=>"15659871332",
                "country"=>"中国",
                "referee"=>"4",
                "proxyLevel"=>"0",
                "capital"=>"0"
            ),
            array(
                "name"=>"linjie3",
                "telephone"=>"15659871332",
                "country"=>"中国",
                "referee"=>"4",
                "proxyLevel"=>"0",
                "capital"=>"0"
            ),
            array(
                "name"=>"linjie3",
                "telephone"=>"15659871332",
                "country"=>"中国",
                "referee"=>"4",
                "proxyLevel"=>"0",
                "capital"=>"0"
            ),
            array(
                "name"=>"linjie3",
                "telephone"=>"15659871332",
                "country"=>"中国",
                "referee"=>"4",
                "proxyLevel"=>"0",
                "capital"=>"0"
            ),
            array(
                "name"=>"linjie3",
                "telephone"=>"15659871332",
                "country"=>"中国",
                "referee"=>"4",
                "proxyLevel"=>"0",
                "capital"=>"0"
            ),
            array(
                "name"=>"linjie3",
                "telephone"=>"15659871332",
                "country"=>"中国",
                "referee"=>"4",
                "proxyLevel"=>"0",
                "capital"=>"0"
            ),
            array(
                "name"=>"linjie3",
                "telephone"=>"15659871332",
                "country"=>"中国",
                "referee"=>"4",
                "proxyLevel"=>"0",
                "capital"=>"0"
            ),
            array(
                "name"=>"linjie3",
                "telephone"=>"15659871332",
                "country"=>"中国",
                "referee"=>"4",
                "proxyLevel"=>"0",
                "capital"=>"0"
            ),
            array(
                "name"=>"linjie3",
                "telephone"=>"15659871332",
                "country"=>"中国",
                "referee"=>"4",
                "proxyLevel"=>"0",
                "capital"=>"0"
            ),
            array(
                "name"=>"linjie3",
                "telephone"=>"15659871332",
                "country"=>"中国",
                "referee"=>"4",
                "proxyLevel"=>"0",
                "capital"=>"0"
            ),
            array(
                "name"=>"linjie3",
                "telephone"=>"15659871332",
                "country"=>"中国",
                "referee"=>"4",
                "proxyLevel"=>"0",
                "capital"=>"0"
            ),
            array(
                "name"=>"linjie3",
                "telephone"=>"15659871332",
                "country"=>"中国",
                "referee"=>"4",
                "proxyLevel"=>"0",
                "capital"=>"0"
            ),
            array(
                "name"=>"linjie3",
                "telephone"=>"15659871332",
                "country"=>"中国",
                "referee"=>"4",
                "proxyLevel"=>"0",
                "capital"=>"0"
            ),
            array(
                "name"=>"linjie3",
                "telephone"=>"15659871332",
                "country"=>"中国",
                "referee"=>"4",
                "proxyLevel"=>"0",
                "capital"=>"0"
            ),
            array(
                "name"=>"linjie3",
                "telephone"=>"15659871332",
                "country"=>"中国",
                "referee"=>"4",
                "proxyLevel"=>"0",
                "capital"=>"0"
            ),
            array(
                "name"=>"linjie3",
                "telephone"=>"15659871332",
                "country"=>"中国",
                "referee"=>"4",
                "proxyLevel"=>"0",
                "capital"=>"0"
            )
        )
    )
);

$arr1=array(
    ["id"=>"1",
        "name"=>"aa",
        "age"=>"111",
        "phone"=>"123456789911"]



);

$json = json_encode($arr);

echo $json;
?>