export const country = function() {
    // body...
    return {
        A: [{ name: 'Afghanistan', number: '+93' },
            { name: 'Albania', number: '+355' },
            { name: 'Algeria', number: '+213' },
            { name: 'American Samoa', number: '+1684' },
            { name: 'Andorra', number: '+376' },
            { name: 'Angola', number: '+244' },
            { name: 'Anguilla', number: '+1264' },
            { name: 'Antartica', number: '+672' },
            { name: 'Antigua and Barbuda', number: '+1268' },
            { name: 'Argentina', number: '+54' },
            { name: 'Armenia', number: '+374' },
            { name: 'Aruba', number: '+297' },
            { name: 'Australia', number: '+61' },
            { name: 'Austria', number: '+43' },
            { name: 'Azerbaijan', number: '+994' }
        ],
        B: [{ name: 'Bahamas', number: '+1242' },
            { name: 'Bahrain', number: '+973' },
            { name: 'Bangladesh', number: '+880' },
            { name: 'Barbados', number: '+1246' },
            { name: 'Belarus', number: '+375' },
            { name: 'Belgium', number: '+32' },
            { name: 'Belize', number: '+501' },
            { name: 'Benin', number: '+229' },
            { name: 'Bermuda', number: '1441' },
            { name: 'Bhutan', number: '+975' },
            { name: 'Bolivia', number: '+591' },
            { name: 'Bosnia and Herzegovina', number: '+387' },
            { name: 'Botswana', number: '+267' },
            { name: 'Brazil', number: '+55' },
            { name: 'British Virgin Islands', number: '+1284' },
            { name: 'Brunei', number: '+673' },
            { name: 'Bulgaria', number: '+359' },
            { name: 'Burkina Faso', number: '+226' },
            { name: 'Burma', number: '+93' },
            { name: 'Burundi', number: '+257' }
        ],
        C: [{ name: 'Cambodia', number: '+855' },
            { name: 'Cameroon', number: '+237' },
            { name: 'Canada', number: '+1' },
            { name: 'Cape Verde', number: '+238' },
            { name: 'Cayman Islands', number: '+1345' },
            { name: 'Central African Republic', number: '+236' },
            { name: 'Chad', number: '+235' },
            { name: 'Chile', number: '+56' },
            { name: 'China', number: '+86' },
            { name: 'Christmas Island', number: '+61' },
            { name: 'Clipperton Island', number: '+676' },
            { name: 'Cocos (Keeling) Islands', number: '+61' },
            { name: 'Colombia', number: '+57' },
            { name: 'Comoros', number: '+269' },
            { name: 'Congo, Democratic Republic of the', number: '+242' },
            { name: 'Congo, Republic of the', number: '+243' },
            { name: 'Cook Islands', number: '+682' },
            { name: 'Costa Rica', number: '+506' },
            { name: 'Cote d\'Ivoire', number: '+225' },
            { name: 'Croatia', number: '+385' },
            { name: 'Cuba', number: '+53' },
            { name: 'Cyprus', number: '+357' },
            { name: 'Czeck Republic', number: '+420' }
        ],
        D: [{ name: 'Denmark', number: '+45' },
            { name: 'Djibouti', number: '+253' },
            { name: 'Dominica', number: '+767' },
            { name: 'Dominican Republic', number: '+1809' }
        ],
        E: [{ name: 'Ecuador', number: '+593' },
            { name: 'Egypt', number: '+20' },
            { name: 'El Salvador', number: '+503' },
            { name: 'Equatorial Guinea', number: '+240' },
            { name: 'Eritrea', number: '+291' },
            { name: 'Estonia', number: '+372' },
            { name: 'Ethiopia', number: '+251' }
        ],
        F: [{ name: 'Falkland Islands (Islas Malvinas)', number: '+500' },
            { name: 'Faroe Islands', number: '+298' },
            { name: 'Fiji', number: '+679' },
            { name: 'Finland', number: '+358' },
            { name: 'France', number: '+33' },
            { name: 'French Guiana', number: '+594' },
            { name: 'French Polynesia', number: '+689' }
        ],
        G: [{ name: 'Gabon', number: '+241' },
            { name: 'Gambia, The', number: '+220' },
            { name: 'Gaza Strip', number: '+970' },
            { name: 'Georgia', number: '+995' },
            { name: 'Germany', number: '+49' },
            { name: 'Ghana', number: '+233' },
            { name: 'Gibraltar', number: '+350' },
            { name: 'Glorioso Islands', number: '+682' },
            { name: 'Greece', number: '+30' },
            { name: 'Greenland', number: '+299' },
            { name: 'Grenada', number: '+1473' },
            { name: 'Guadeloupe', number: '+590' },
            { name: 'Guam', number: '+1671' },
            { name: 'Guatemala', number: '+502' },
            { name: 'Guernsey', number: '+44' },
            { name: 'Guinea', number: '+224' },
            { name: 'Guinea-Bissau', number: '+245' },
            { name: 'Guyana', number: '+592' }
        ],
        H: [{ name: 'Haiti', number: '+509' },
            { name: 'Holy See (Vatican City)', number: '+379' },
            { name: 'Honduras', number: '+504' },
            { name: 'Hong Kong', number: '+852' }, { name: 'Hungary', number: '+36' }
        ],
        I: [{ name: 'Iceland', number: '+354' },
            { name: 'India', number: '+91' },
            { name: 'Indonesia', number: '+62' },
            { name: 'Iran', number: '+98' },
            { name: 'Iraq', number: '+964' },
            { name: 'Ireland', number: '+353' },
            { name: 'Israel', number: '+972' },
            { name: 'Italy', number: '+39' }
        ],
        J: [{ name: 'Jamaica', number: '+1876' },
            { name: 'Japan', number: '+81' },
            { name: 'Jersey', number: '+44' },
            { name: 'Jordan', number: '+962' }
        ],
        K: [{ name: 'Kazakhstan', number: '+7' },
            { name: 'Kenya', number: '+254' },
            { name: 'Kiribati', number: '+686' },
            { name: 'Korea, North', number: '+850' },
            { name: 'Korea, South', number: '+82' },
            { name: 'Kuwait', number: '+965' },
            { name: 'Kyrgyzstan', number: '+996' }
        ],
        L: [{ name: 'Laos', number: '+856' },
            { name: 'Latvia', number: '+371' },
            { name: 'Lebanon', number: '+961' },
            { name: 'Lesotho', number: '+266' },
            { name: 'Liberia', number: '+231' },
            { name: 'Libya', number: '+218' },
            { name: 'Liechtenstein', number: '+423' },
            { name: 'Lithuania', number: '+370' },
            { name: 'Luxembourg', number: '+352' }
        ],
        M: [{ name: 'Macau', number: '+853' },
            { name: 'Macedonia, Former Yugoslav Republic of', number: '+389' },
            { name: 'Madagascar', number: '+261' },
            { name: 'Malawi', number: '+265' },
            { name: 'Malaysia', number: '+60' },
            { name: 'Maldives', number: '+960' },
            { name: 'Mali', number: '+223' },
            { name: 'Malta', number: '+356' }, { name: 'Marshall Islands', number: '+692' },
            { name: 'Martinique', number: '+596' },
            { name: 'Mauritania', number: '+222' },
            { name: 'Mauritius', number: '+230' },
            { name: 'Mayotte', number: '+262' },
            { name: 'Mexico', number: '+52' },
            { name: 'Micronesia, Federated States of', number: '+691' },
            { name: 'Moldova', number: '+373' },
            { name: 'Monaco', number: '+377' },
            { name: 'Mongolia', number: '+976' },
            { name: 'Montserrat', number: '+1664' },
            { name: 'Morocco', number: '+212' },
            { name: 'Mozambique', number: '+258' }
        ],
        N: [{ name: 'Namibia', number: '+264' },
            { name: 'Nauru', number: '+674' },
            { name: 'Nepal', number: '+977' },
            { name: 'Netherlands', number: '+31' },
            { name: 'New Caledonia', number: '+687' },
            { name: 'New Zealand', number: '+64' },
            { name: 'Nicaragua', number: '+505' },
            { name: 'Niger', number: '+227' },
            { name: 'Nigeria', number: '+234' },
            { name: 'Niue', number: '+683' },
            { name: 'Norfolk Island', number: '+672' },
            { name: 'Northern Mariana Islands', number: '+1670' },
            { name: 'Norway', number: '+47' }
        ],
        O: [{ name: 'Oman', number: '+968' }],
        P: [{ name: 'Pakistan', number: '+92' },
            { name: 'Palau', number: '+680' },
            { name: 'Panama', number: '+507' },
            { name: 'Papua New Guinea', number: '+675' },
            { name: 'Paraguay', number: '+595' },
            { name: 'Peru', number: '+51' },
            { name: 'Philippines', number: '+63' },
            { name: 'Poland', number: '+48' },
            { name: 'Portugal', number: '+351' },
            { name: 'Puerto Rico', number: '+1' }
        ],
        Q: [{ name: 'Qatar', number: '+974' }],
        R: [{ name: 'Reunion', number: '+262' },
            { name: 'Romainia', number: '+40' },
            { name: 'Russia', number: '+7' },
            { name: 'Rwanda', number: '+250' }
        ],
        S: [{ name: 'Saint Helena', number: '+290' },
            { name: 'Saint Kitts and Nevis', number: '+1869' },
            { name: 'Saint Lucia', number: '+1758' },
            { name: 'Saint Pierre and Miquelon', number: '+508' },
            { name: 'Saint Vincent and the Grenadines', number: '+1784' },
            { name: 'Samoa', number: '+685' },
            { name: 'San Marino', number: '+378' },
            { name: 'Sao Tome and Principe', number: '+239' },
            { name: 'Saudi Arabia', number: '+966' },
            { name: 'Senegal', number: '+221' },
            { name: 'Seychelles', number: '+248' },
            { name: 'Sierra Leone', number: '+232' },
            { name: 'Singapore', number: '+65' },
            { name: 'Slovakia', number: '+421' },
            { name: 'Slovenia', number: '+386' },
            { name: 'Solomon Islands', number: '+677' },
            { name: 'Somalia', number: '+252' },
            { name: 'South Africa', number: '+27' },
            { name: 'Spain', number: '+34' },
            { name: 'Sri Lanka', number: '+94' },
            { name: 'Sudan', number: '+249' },
            { name: 'Suriname', number: '+597' },
            { name: 'Svalbard', number: '+47' },
            { name: 'Swaziland', number: '+268' },
            { name: 'Sweden', number: '+46' },
            { name: 'Switzerland', number: '+41' },
            { name: 'Syria', number: '+963' }
        ],
        T: [{ name: 'Taiwan', number: '+885' },
            { name: 'Tajikistan', number: '+992' },
            { name: 'Tanzania', number: '+255' },
            { name: 'Thailand', number: '+66' },
            { name: 'Tobago', number: '+670' },
            { name: 'Toga', number: '+228' },
            { name: 'Tokelau', number: '+690' },
            { name: 'Tonga', number: '+676' },
            { name: 'Trinidad', number: '+1868' },
            { name: 'Tunisia', number: '+216' },
            { name: 'Turkey', number: '+90' },
            { name: 'Turkmenistan', number: '+993' },
            { name: 'Tuvalu', number: '+688' }
        ],
        U: [{ name: 'Uganda', number: '+256' },
            { name: 'Ukraine', number: '+380' },
            { name: 'United Arab Emirates', number: '+971' },
            { name: 'United Kingdom', number: '+44' },
            { name: 'Uruguay', number: '+598' },
            { name: 'Uzbekistan', number: '+998' }
        ],
        V: [{ name: 'Vanuatu', number: '+678' },
            { name: 'Venezuela', number: '+58' },
            { name: 'Vietnam', number: '+84' }
        ],
        W: [{ name: 'Wales', number: '+61' },
            { name: 'Wallis and Futuna', number: '+681' },
            { name: 'Western Sahara', number: '+212' }
        ],
        Y: [{ name: 'Yemen', number: '+967' },
            { name: 'Yugoslavia', number: '+338' }
        ],
        Z: [{ name: 'Zambia', number: '+260' },
            { name: 'Zimbabwe', number: '+263' }
        ]
    }
};
export const cnCountry = function() {
    return {
        A: [{ name: '阿尔巴尼亚', number: '+355' },
            { name: '阿尔及利亚', number: '+213' },
            { name: '阿富汗', number: '+93' },
            { name: '爱尔兰', number: '+353' },
            { name: '埃及', number: '+20' },
            { name: '埃塞俄比亚', number: '+251' },
            { name: '爱沙尼亚', number: '+372' },
            { name: '阿联酋', number: '+971' },
            { name: '阿鲁巴', number: '+297' },
            { name: '阿曼', number: '+968' },
            { name: '安道尔', number: '+376' },
            { name: '安哥拉', number: '+244' },
            { name: '安圭拉', number: '+1264' },
            { name: '澳大利亚', number: '+61' },
            { name: '奥地利', number: '+43' },
            { name: '阿塞拜疆', number: '+994' },
            { name: '阿森松岛', number: '+247' }
        ],
        B: [{ name: '巴巴多斯', number: '+1268' },
            { name: '巴哈马', number: '+1242' },
            { name: '白俄罗斯', number: '+375' },
            { name: '百慕大三角', number: '+1441' },
            { name: '巴基斯坦', number: '+92' },
            { name: '巴勒斯坦', number: '+970' },
            { name: '巴林', number: '+973' },
            { name: '巴拿马', number: '+507' },
            { name: '保加利亚', number: '+359' },
            { name: '巴西', number: '+55' },
            { name: '贝宁', number: '+229' },
            { name: '比利时', number: '+32' },
            { name: '冰岛', number: '+354' },
            { name: '博茨瓦纳', number: '+267' },
            { name: '波多黎各', number: '1787' },
            { name: '波兰', number: '+48' },
            { name: '伯利兹', number: '+501' },
            { name: '不丹', number: '+975' },
            { name: '布基纳法索', number: '+226' },
            { name: '布隆迪', number: '+257' }
        ],
        C: [{ name: '朝鲜', number: '+850' },
            { name: '赤道几内亚', number: '+240' }
        ],
        D: [{ name: '丹麦', number: '+45' },
            { name: '德国', number: '+49' },
            { name: '东帝汶', number: '+670' },
            { name: '多哥', number: '+228' },
            { name: '多米尼加', number: '+1849' }
        ],
        E: [{ name: '厄立特里亚', number: '+291' },
            { name: '俄罗斯', number: '+7' }
        ],
        F: [{ name: '法国', number: '+33' },
            { name: '法罗群岛', number: '+298' },
            { name: '梵蒂冈', number: '+396' },
            { name: '斐济群岛', number: '+679' },
            { name: '菲律宾', number: '+63' },
            { name: '芬兰', number: '+358' },
            { name: '佛得角', number: '+238' }
        ],
        G: [{ name: '冈比亚', number: '+220' },
            { name: '格陵兰', number: '+299' },
            { name: '格林纳达', number: '1473' },
            { name: '格鲁吉亚', number: '+995' },
            { name: '哥斯达黎加', number: '+506' },
            { name: '瓜德罗普', number: '+590' },
            { name: '关岛', number: '+1671' },
            { name: '古巴', number: '+53' }
        ],
        H: [{ name: '海地', number: '+509' },
            { name: '韩国', number: '+82' },
            { name: '黑山', number: '+382' },
            { name: '荷兰', number: '+31' },
            { name: '洪都拉斯', number: '+504' }
        ],
        I: [],
        J: [{ name: '加拿大', number: '+1' },
            { name: '加纳', number: '+233' },
            { name: '柬埔寨', number: '+855' },
            { name: '加蓬', number: '+241' },
            { name: '吉布提', number: '+253' },
            { name: '捷克', number: '+420' },
            { name: '基里巴斯', number: '+686' },
            { name: '几内亚', number: '+224' },
            { name: '几内亚比绍', number: '+245' },
            { name: '津巴布韦', number: '+263' }
        ],
        K: [{ name: '开曼群岛', number: '+1345' },
            { name: '喀麦隆', number: '+237' },
            { name: '卡塔尔', number: '+974' },
            { name: '克罗地亚', number: '+385' },
            { name: '科摩罗', number: '+269' },
            { name: '肯尼亚', number: '+254' },
            { name: '科特迪瓦', number: '+225' },
            { name: '科威特', number: '+965' },
            { name: '库克群岛', number: '+682' }
        ],
        L: [{ name: '莱索托', number: '+266' },
            { name: '老挝', number: '+856' },
            { name: '拉脱维亚', number: '+371' },
            { name: '黎巴嫩', number: '+961' },
            { name: '利比里亚', number: '+231' },
            { name: '利比亚', number: '+218' },
            { name: '列支敦士登', number: '+4175' },
            { name: '立陶宛', number: '+370' },
            { name: '留尼旺岛', number: '+262' },
            { name: '罗马尼亚', number: '+40' },
            { name: '卢森堡', number: '+352' },
            { name: '卢旺达', number: '+250' }
        ],
        M: [{ name: '马达加斯加', number: '+261' },
            { name: '马尔代夫', number: '+960' },
            { name: '马耳他', number: '+356' },
            { name: '马来西亚', number: '+60' },
            { name: '马拉维', number: '+265' },
            { name: '马里', number: '+223' },
            { name: '毛里求斯', number: '+230' },
            { name: '毛里塔尼亚', number: '+222' },
            { name: '马其顿', number: '+389' },
            { name: '马绍尔群岛', number: '+692' },
            { name: '马提尼克', number: '+596' },
            { name: '美国', number: '+1' },
            { name: '美属萨摩亚', number: '+684' },
            { name: '蒙古', number: '+976' },
            { name: '孟加拉', number: '+880' },
            { name: '蒙特塞拉特', number: '1664' },
            { name: '摩尔多瓦', number: '+373' },
            { name: '摩洛哥', number: '+212' },
            { name: '摩纳哥', number: '+377' },
            { name: '莫桑比克', number: '+258' },
            { name: '墨西哥', number: '+52' }
        ],
        N: [{ name: '纳米比亚', number: '+264' },
            { name: '南非', number: '+27' },
            { name: '南苏丹', number: '+211' },
            { name: '瑙鲁', number: '+674' },
            { name: '尼泊尔', number: '+977' },
            { name: '尼加拉瓜', number: '+505' },
            { name: '尼日尔', number: '+227' },
            { name: '尼日利亚', number: '+234' },
            { name: '纽埃岛', number: '+683' },
            { name: '诺福克岛', number: '+6723' },
            { name: '挪威', number: '+47' }
        ],
        O: [],
        P: [{ name: '帕劳', number: '+680' },
            { name: '葡萄牙', number: '+351' }
        ],
        Q: [],
        R: [{ name: '日本', number: '+81' },
            { name: '瑞典', number: '+46' },
            { name: '瑞士', number: '+41' },
            { name: '瑞士', number: '+41' }
        ],
        S: [{ name: '萨尔瓦多', number: '+503' },
            { name: '塞尔维亚', number: '+381' },
            { name: '塞拉利昂', number: '+232' },
            { name: '塞内加尔', number: '+221' },
            { name: '塞浦路斯', number: '+357' },
            { name: '塞舌尔', number: '+248' },
            { name: '萨摩亚', number: '+685' },
            { name: '沙特阿拉伯', number: '+966' },
            { name: '圣赫勒拿岛', number: '+290' },
            { name: '圣卢西亚', number: '+1758' },
            { name: '圣马力诺', number: '+378' },
            { name: '斯里兰卡', number: '+94' },
            { name: '斯洛伐克', number: '+421' },
            { name: '斯威士兰', number: '+268' },
            { name: '苏丹', number: '+249' },
            { name: '所罗门群岛', number: '+677' },
            { name: '索马里', number: '+252' }
        ],
        T: [{ name: '泰国', number: '+66' },
            { name: '塔吉克斯坦', number: '+992' },
            { name: '汤加', number: '+676' },
            { name: '坦桑尼亚', number: '+255' },
            { name: '土耳其', number: '+90' },
            { name: '土库曼斯坦', number: '+993' },
            { name: '突尼斯', number: '+216' },
            { name: '托克劳', number: '+690' },
            { name: '图瓦卢', number: '+688' }
        ],
        W: [{ name: '瓦努阿图', number: '+678' },
            { name: '危地马拉', number: '+502' },
            { name: '委内瑞拉', number: '+58' },
            { name: '文莱', number: '+673' },
            { name: '乌干达', number: '+256' },
            { name: '乌克兰', number: '+380' }
        ],
        X: [{ name: '西班牙', number: '+34' },
            { name: '希腊', number: '+30' },
            { name: '新加坡', number: '+65' },
            { name: '新西兰', number: '+64' },
            { name: '匈牙利', number: '+36' },
            { name: '西撒哈拉', number: '+210' },
            { name: '叙利亚', number: '+963' }
        ],
        Y: [{ name: '牙买加', number: '+1876' },
            { name: '亚美尼亚', number: '+374' },
            { name: '也门', number: '+967' },
            { name: '意大利', number: '+39' },
            { name: '伊拉克', number: '+964' },
            { name: '伊朗', number: '+98' },
            { name: '印度', number: '+91' },
            { name: '印度尼西亚', number: '+62' },
            { name: '英国', number: '+44' },
            { name: '以色列', number: '+972' },
            { name: '约旦', number: '+962' },
            { name: '越南', number: '+84' }
        ],
        Z: [{ name: '赞比亚', number: '+260' },
            { name: '乍得', number: '+235' },
            { name: '中非', number: '+236' },
            { name: '中国', number: '+86' },
            { name: '中国香港', number: '+852' },
            { name: '中国澳门', number: '+853' },
            { name: '中国台湾', number: '+886' }
        ]
    }
};
export const getParamsFromURL = function (URL) {//获取URL中的参数
    // alert(JSON.stringify(URL))
    URL = URL ? URL : window.location;
    var paramObject = {};
    console.log(window.location.search)
    alert(JSON.stringify(URL.search))
    var paramStr = URL.search.substring(2);
    var params = paramStr.split('&');
    for (var i = 0; i < params.length; i++) {
        var pair = params[i].split('=');
        paramObject[pair[0]] = pair[1];
        paramObject[pair[0]] = decodeURI(paramObject[pair[0]]);
    }
    return paramObject;
};
